include:
- project: iiidevops-templates/ci-template
  file: ci/template.gitlab-ci.yml
- project: iiidevops-templates/ci-template
  file: job/DeployDatabase.gitlab-ci.yml
stages:
- initial
- scan
- build
- deploy
- test
Test--SonarQube source code scan:
  variables:
    iiidevops: sonarqube
    CHART_TYPE: normal
  only:
  - master
Test--Checkmarx source code scan:
  variables:
    iiidevops: checkmarx
  only:
  - master
Deploy--Database:
  variables:
    iiidevops: deployed-environments
    CHART_DB_GUI: 'true'
    CHART_DB_NAME: todo_db
    CHART_DB_USERNAME: iiidevops
    CHART_DB_PASSWORD: DevOps_123
    CHART_DB_TAG: 4.4-debian-10
    CHART_DB_TYPE: mongodb
    CHART_NFS_ENABLED: 'false'
    CHART_NFS_SERVER_IP: 10.20.0.100
    CHART_VERSION: 0.4.1
  only:
  - master
Deploy--Wait DB deployment:
  variables:
    iiidevops: deployed-environments
    max_wait: 128
  only:
  - master
Build image:
  variables:
    iiidevops: deployed-environments
  only:
  - master
Build--Scan docker image:
  variables:
    iiidevops: deployed-environments
  only:
  - master
Deploy--Set environment and wait deployment:
  variables:
    iiidevops: deployed-environments
  needs:
  - Deploy--Wait DB deployment
  only:
  - master
Deploy--Web:
  variables:
    iiidevops: deployed-environments
    CHART_WEB_PORT: 8080
    CHART_PROXY_BODY_SIZE: 1m
    CHART_DB_NAME: todo_db
    CHART_DB_USERNAME: iiidevops
    CHART_DB_PASSWORD: DevOps_123
    CHART_DB_SERVER: ${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-db
  needs:
  - Deploy--Wait DB deployment
  only:
  - master
Test--Anchore SBOM:
  variables:
    iiidevops: anchore
  only:
  - master
Test--ZAP:
  variables:
    iiidevops: zap
    CHART_WEB_PORT: 8080
  only:
  - master
Test--WebInspect:
  variables:
    iiidevops: webinspect
  only:
  - skip
Test--Postman:
  variables:
    iiidevops: postman
    CHART_WEB_PORT: 8080
  only:
  - master
Test--Sideex:
  variables:
    iiidevops: sideex
    CHART_WEB_PORT: 8080
  only:
  - master
